os:
- osx
language: generic
osx_image: xcode9
cache:
  - bundler
  - cocoapods
before_install:
  - brew update
  - ./Scripts/bootstrap
script:
  - buck tests
  - buck build app
branches:
  only:
    - master
