os:
  - osx
language: generic
osx_image: xcode9.1
cache:
  - bundler
  - cocoapods
before_install:
  - brew tap facebook/fb
  - brew install buck
  - buck --version
install: cd Dependencies && pod install
script:
  - buck test
  - buck build app
branches:
  only:
    - master
