os:
  - osx
language: generic
osx_image: xcode9.1
podfile: Dependencies/Podfile
cache:
  - bundler
  - cocoapods
before_install:
  - brew tap facebook/fb
  - brew install buck
  - buck --version
script:
  - buck tests
  - buck build app
branches:
  only:
    - master
